version: 2

builds:
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
  - id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    skip: "{{ eq .Env.SCOOP_ONLY \"1\" }}"
    ldflags:
      - -s -w
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    skip: "{{ eq .Env.SCOOP_ONLY \"1\" }}"
    ldflags:
      - -s -w

archives:
  - format_overrides:
      - goos: windows
        formats: [zip]

scoops:
  - repository:
      owner: olivier-w
      name: scoop-bucket
    homepage: https://github.com/olivier-w/climp
    description: Minimal CLI media player
    license: Apache-2.0

release:
  replace_existing_artifacts: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
